# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: diff.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 30, 0, "", "diff.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\ndiff.proto\x12\x08\x64ocdelta"\x1c\n\x0c\x44ocumentPath\x12\x0c\n\x04path\x18\x01 \x01(\t",\n\x0c\x44ocumentPair\x12\r\n\x05path1\x18\x01 \x01(\t\x12\r\n\x05path2\x18\x02 \x01(\t"\x18\n\x08\x44iffJson\x12\x0c\n\x04json\x18\x01 \x01(\t"1\n\rExtractedPage\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x12\n\nparagraphs\x18\x02 \x03(\t"\x1e\n\x0c\x44iffResponse\x12\x0e\n\x06result\x18\x01 \x01(\t""\n\x0fSummaryResponse\x12\x0f\n\x07summary\x18\x01 \x01(\t2\xce\x01\n\x0b\x44iffService\x12@\n\x0b\x45xtractText\x12\x16.docdelta.DocumentPath\x1a\x17.docdelta.ExtractedPage0\x01\x12=\n\x0b\x43omputeDiff\x12\x16.docdelta.DocumentPair\x1a\x16.docdelta.DiffResponse\x12>\n\rSummarizeDiff\x12\x12.docdelta.DiffJson\x1a\x19.docdelta.SummaryResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "diff_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_DOCUMENTPATH"]._serialized_start = 24
    _globals["_DOCUMENTPATH"]._serialized_end = 52
    _globals["_DOCUMENTPAIR"]._serialized_start = 54
    _globals["_DOCUMENTPAIR"]._serialized_end = 98
    _globals["_DIFFJSON"]._serialized_start = 100
    _globals["_DIFFJSON"]._serialized_end = 124
    _globals["_EXTRACTEDPAGE"]._serialized_start = 126
    _globals["_EXTRACTEDPAGE"]._serialized_end = 175
    _globals["_DIFFRESPONSE"]._serialized_start = 177
    _globals["_DIFFRESPONSE"]._serialized_end = 207
    _globals["_SUMMARYRESPONSE"]._serialized_start = 209
    _globals["_SUMMARYRESPONSE"]._serialized_end = 243
    _globals["_DIFFSERVICE"]._serialized_start = 246
    _globals["_DIFFSERVICE"]._serialized_end = 452
# @@protoc_insertion_point(module_scope)
