# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import diff_pb2 as diff__pb2

GRPC_GENERATED_VERSION = "1.72.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in diff_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class DiffServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExtractText = channel.unary_stream(
            "/docdelta.DiffService/ExtractText",
            request_serializer=diff__pb2.DocumentPath.SerializeToString,
            response_deserializer=diff__pb2.ExtractedPage.FromString,
            _registered_method=True,
        )
        self.ComputeDiff = channel.unary_unary(
            "/docdelta.DiffService/ComputeDiff",
            request_serializer=diff__pb2.DocumentPair.SerializeToString,
            response_deserializer=diff__pb2.DiffResponse.FromString,
            _registered_method=True,
        )
        self.SummarizeDiff = channel.unary_unary(
            "/docdelta.DiffService/SummarizeDiff",
            request_serializer=diff__pb2.DiffJson.SerializeToString,
            response_deserializer=diff__pb2.SummaryResponse.FromString,
            _registered_method=True,
        )


class DiffServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExtractText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ComputeDiff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SummarizeDiff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DiffServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ExtractText": grpc.unary_stream_rpc_method_handler(
            servicer.ExtractText,
            request_deserializer=diff__pb2.DocumentPath.FromString,
            response_serializer=diff__pb2.ExtractedPage.SerializeToString,
        ),
        "ComputeDiff": grpc.unary_unary_rpc_method_handler(
            servicer.ComputeDiff,
            request_deserializer=diff__pb2.DocumentPair.FromString,
            response_serializer=diff__pb2.DiffResponse.SerializeToString,
        ),
        "SummarizeDiff": grpc.unary_unary_rpc_method_handler(
            servicer.SummarizeDiff,
            request_deserializer=diff__pb2.DiffJson.FromString,
            response_serializer=diff__pb2.SummaryResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "docdelta.DiffService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("docdelta.DiffService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class DiffService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExtractText(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/docdelta.DiffService/ExtractText",
            diff__pb2.DocumentPath.SerializeToString,
            diff__pb2.ExtractedPage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ComputeDiff(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/docdelta.DiffService/ComputeDiff",
            diff__pb2.DocumentPair.SerializeToString,
            diff__pb2.DiffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SummarizeDiff(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/docdelta.DiffService/SummarizeDiff",
            diff__pb2.DiffJson.SerializeToString,
            diff__pb2.SummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
